### ISSUE TITLE
Consider releasing this package on npm

### ISSUE THREAD

**Issue by Punie** [homebound-team/graphql-typescript-scalar-type-policies#1]
Hello there 👋 

First of all, thank you for this amazing [graphql-codegen](https://graphql-code-generator.com/) plugin, it has been tremendously helpful for handling our API's custom scalars in one single location.

My question then is would you consider releasing this on npm (even as a v0.1) to avoid pulling dependencies straight from github?
If the answer is no because you consider this plugin not mature enough, what could I do to help move this forward eventually?

Thank you for your time ♥️

**Comment by mbrowne** [comment]
Looks like it was published on npm:
https://www.npmjs.com/package/@thx/graphql-typescript-scalar-type-policies

**Comment by tubbo** [comment]
yes please...would really like to see an actual release. seems like someone else took the opportunity but it has no connection to this repo and therefore cannot be trusted quite as much as if the releases came from this repo.

**Comment by larrifax** [comment]
Just wanted to chime in to see if there's any progress on this issue? Seems like @stephenh is the person that can provide answers about the future of this repository/package. 

I would really appreciate it if this could become an official npm package from the @homebound team, especially now that the unofficial package lags behind master, which causes us to download an old major version of `@graphql-codegen/plugin-helpers`.

**Comment by stephenh** [comment]
Oh jeez guys, sorry, we didn't realize the npm package was still private; it is public now:

https://www.npmjs.com/package/@homebound/graphql-typescript-scalar-type-policies

Also the github email alerts had gone into the black hole of ~1000s of our internal github email notifications, so I'd missed all of these comments...sorry about that! :-|

**Comment by stephenh** [comment]
Fyi/thanks @MrDesjardins , it was your blog post, linked to from https://github.com/apollographql/apollo-feature-requests/issues/368, that made me realize we were black holing these notifications. Our repo is public, and I'm setting up appropriate gmail filters to not miss these going forward.
